server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/idealplanner
    username: postgres
    password: 7426
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
